"""
Django settings for Excel project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if load_dotenv:
    load_dotenv(BASE_DIR / '.env')


def _env(key: str, default: str | None = None) -> str | None:
    return os.getenv(key, default)


def _env_bool(key: str, default: bool = False) -> bool:
    val = os.getenv(key)
    if val is None:
        return default
    return val.strip().lower() in ('1', 'true', 'yes', 'y', 'on')


ENVIRONMENT = (_env('ENVIRONMENT', 'dev') or 'dev').strip().lower()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

SECRET_KEY = _env('SECRET_KEY', 'django-insecure-change-me-in-env')  # set in .env in prod
DEBUG = _env_bool('DEBUG', False)

_allowed_hosts = _env('ALLOWED_HOSTS', '127.0.0.1,localhost,bibletrivia.pythonanywhere.com')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',') if h.strip()]

_csrf_trusted_origins = _env('CSRF_TRUSTED_ORIGINS', 'https://bibletrivia.pythonanywhere.com')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted_origins.split(',') if o.strip()]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'users',
    'core',
    'Exam',
    'accounts',
    'transport',
    'communication',
    'hostels',
    'e_learning',
    'cafe',
    'attendance',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.GlobalErrorHandlingMiddleware',
]

ROOT_URLCONF = 'Excel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.user_flags_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'Excel.wsgi.application'


if ENVIRONMENT == 'dev':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': _env('MYSQL_DATABASE', ''),
            'USER': _env('MYSQL_USER', ''),
            'PASSWORD': _env('MYSQL_PASSWORD', ''),
            'HOST': _env('MYSQL_HOST', '127.0.0.1'),
            'PORT': _env('MYSQL_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    }

# Production Security Settings (Enabled only in production)
if ENVIRONMENT != 'dev':
    SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # HSTS settings (Only enable after verifying SSL works perfectly)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.MyUser'

LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'core:dashboard'
LOGOUT_REDIRECT_URL = 'users:login'

# M-Pesa Integration Settings
MPESA_ENVIRONMENT = (_env('MPESA_ENVIRONMENT') or 'sandbox').strip()
MPESA_CONSUMER_KEY = (_env('MPESA_CONSUMER_KEY') or '').strip()
MPESA_CONSUMER_SECRET = (_env('MPESA_CONSUMER_SECRET') or '').strip()
MPESA_PASSKEY = (_env('MPESA_PASSKEY') or '').strip()
MPESA_SHORTCODE = (_env('MPESA_SHORTCODE') or '').strip()
MPESA_INITIATOR_NAME = (_env('MPESA_INITIATOR_NAME') or '').strip()
MPESA_INITIATOR_PASSWORD = (_env('MPESA_INITIATOR_PASSWORD') or '').strip()
MPESA_SECURITY_CREDENTIAL = (_env('MPESA_SECURITY_CREDENTIAL') or '').strip()
MPESA_CALLBACK_URL = (_env('MPESA_CALLBACK_URL') or '').strip()
MPESA_RESULT_URL = (_env('MPESA_RESULT_URL') or '').strip()
MPESA_QUEUE_TIMEOUT_URL = (_env('MPESA_QUEUE_TIMEOUT_URL') or '').strip()

# Security settings for large forms (like multi-student admin pages)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# OpenAI API key for AI-powered short-answer grading
OPENAI_API_KEY = (_env('OPENAI_API_KEY') or '').strip()

# Media files (question images, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# TextSMS Integration Settings
TEXT_SMS_API_KEY = (_env('TEXT_SMS_API_KEY') or '').strip()
TEXT_SMS_PARTNER_ID = (_env('TEXT_SMS_PARTNER_ID') or '').strip()
TEXT_SMS_SHORTCODE = (_env('TEXT_SMS_SHORTCODE') or 'SENDERID').strip()
# Email Backend for development
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
