from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('teacher/dashboard/', views.TeacherDashboardView.as_view(), name='teacher-dashboard'),
    path('guardian/dashboard/', views.guardian_dashboard, name='guardian-dashboard'),
    path('students/', views.StudentsListView.as_view(), name='students-list'),
    path('students/promote/', views.StudentPromotionView.as_view(), name='student-promotion'),
    path('guardians/', views.GuardianListView.as_view(), name='guardian-list'),
    path('student/create/', views.create_student, name='create-student'),
    path('student/<int:pk>/', views.StudentDetailView.as_view(), name='student-detail'),
    path('student/<int:pk>/update/', views.update_student, name='update-student'),
    path('student/<int:pk>/delete/', views.delete_student, name='delete-student'),
    path('classes/', views.ClassesListView.as_view(), name='classes-list'),
    path('class/<int:pk>/', views.ClassDetailView.as_view(), name='class-detail'),
    path('class/<int:class_id>/analytics/', views.class_exam_analytics, name='class-exam-analytics'),
    path('class/<int:class_id>/merit-list/', views.class_merit_list, name='class-merit-list'),
    path('class/<int:class_id>/subject/<int:subject_id>/exam/<int:exam_id>/analytics/', views.subject_exam_analytics, name='subject-exam-analytics'),
    path('configurations/', views.configurations, name='configurations'),
    path('configurations/academic-year/create/', views.create_academic_year, name='create-academic-year'),
    path('configurations/term/create/', views.create_term, name='create-term'),
    path('configurations/term/update/', views.update_term, name='update-term'),
    path('configurations/grade/create/', views.create_grade, name='create-grade'),
    path('configurations/class/create/', views.create_class, name='create-class'),
    path('configurations/class/update/', views.update_class, name='update-class'),
    path('configurations/exam/create/', views.create_exam, name='create-exam'),
    path('configurations/fee-structure/create/', views.create_fee_structure, name='create-fee-structure'),
    path('configurations/fee-structure/update/', views.update_fee_structure, name='update-fee-structure'),
    path('configurations/additional-charge/create/', views.create_additional_charge, name='create-additional-charge'),
    path('configurations/additional-charge/update/', views.update_additional_charge, name='update-additional-charge'),
    path('configurations/auxiliary-service-type/create/', views.create_auxiliary_service_type, name='create-auxiliary-service-type'),
    path('configurations/auxiliary-service-type/update/', views.update_auxiliary_service_type, name='update-auxiliary-service-type'),
    path('configurations/exam-mode/<int:exam_mode_id>/update/', views.update_exam_mode, name='update-exam-mode'),
    path('configurations/delete/<str:model_type>/<int:item_id>/', views.delete_item, name='delete-item'),
    path('student/<int:student_id>/report/<int:exam_id>/', views.student_report, name='student-report'),
    path('class/<int:class_id>/bulk-reports/<int:exam_id>/', views.bulk_class_reports, name='bulk-class-reports'),
    path('payments/', views.manage_fee_payments, name='manage-fee-payments'),
    path('payments/process/<int:student_id>/', views.process_payment, name='process-payment'),
    path('payments/receipt/<int:payment_id>/', views.payment_receipt, name='payment-receipt'),
    path('attendance/<int:class_id>/', views.mark_attendance, name='mark-attendance'),
    path('attendance/<int:class_id>/<str:date>/', views.attendance_detail, name='attendance-detail'),
    path('attendance/data/', views.get_attendance_data, name='get-attendance-data'),
    path('attendance/analytics/', views.AttendanceAnalyticsView.as_view(), name='attendance-analytics'),
    path('attendance/notify-late/', views.SendLatenessSMSView.as_view(), name='send-lateness-sms'),

    path('ajax/get-school-classes/', views.get_school_classes, name='get-school-classes'),
    path('ajax/get-school-routes/', views.get_school_routes, name='get-school-routes'),
    path('ajax/fee-structure-preview/', views.fee_structure_preview, name='fee-structure-preview'),
    path('ajax/get-class-exclusion-list/<int:class_id>/<int:exam_id>/', views.get_class_exclusion_list, name='get-class-exclusion-list'),
    path('ajax/update-exclusions/', views.update_exclusions, name='update-exclusions'),
    path('schools-analytics/', views.schools_analytics, name='schools-analytics'),
    path('discipline/', views.discipline_log, name='discipline-log'),
    path('configurations/academic-year/<int:year_id>/activate/', views.activate_academic_year, name='activate-academic-year'),
    path('configurations/migrate-year/', views.migrate_year, name='migrate-year'),
    path('configurations/revert-year-migration/', views.revert_year_migration, name='revert-year-migration'),
    path('configurations/term/<int:term_id>/activate/', views.activate_term, name='activate-term'),
    path('reports/', views.ReportDashboardView.as_view(), name='reports'),
    path('operations/', views.operations_dashboard, name='operations'),
    path('finance/', views.finance_dashboard, name='finance'),
    path('system-control/', views.system_control_dashboard, name='system-control'),
    
    # Expense Management
    path('expenses/', views.expenses_list, name='expenses-list'),
    path('expenses/create/', views.create_expense, name='create-expense'),
    path('expenses/delete/<int:pk>/', views.delete_expense, name='delete-expense'),
    
    path('link-student/', views.link_student_view, name='link-student'),
    path('student/<int:pk>/update-status/', views.update_student_status, name='update-student-status'),
    path('logs/', views.logs_list, name='system-logs'),
    path('api/student-search/', views.student_search_api, name='student-search-api'),
    path('finance/payments/history/', views.FeePaymentListView.as_view(), name='payment-history'),
]
