server {
    listen 80;
    server_name excel-schools.com www.excel-schools.com 137.184.58.240;

    client_max_body_size 50M;

    # Django Media files
    location /media/ {
        alias /var/www/excel-schools/media/;
    }

    # Django Static files
    location /static/ {
        alias /var/www/excel-schools/staticfiles/;
    }

    # Proxy to Gunicorn
    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
