name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: '137.184.58.240'
          username: 'root'
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /var/www/excel-schools
            git pull origin main
            source venv/bin/activate
            python manage.py makemigrations
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
